#!/bin/bash

#SBATCH --account=cta
#SBATCH --partition=cpu
#SBATCH --get-user-env
#SBATCH --wait-all-nodes=1

#SBATCH --array=15-93
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --dependency=singleton

#SBATCH --time=00:30:00
#SBATCH --mem-per-cpu=512MB

#SBATCH -J simtel_flat_spectrum_array_01

export OMP_NUM_THREADS=1
cd $SLURM_SUBMIT_DIR
ulimit -s unlimited

~/cta/CTA-Simulation/scripts/prod4_sst-astri+chec-s_sim ${SLURM_ARRAY_TASK_ID}
