#!/bin/bash

#SBATCH --account=cta
#SBATCH --partition=cpu
#SBATCH --get-user-env
#SBATCH --wait-all-nodes=1

#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --dependency=singleton

#SBATCH --time=00:15:00
#SBATCH --mem-per-cpu=512MB

#SBATCH -J simtel_estimate_01

#SBATCH --mail-user=a1648400@adelaide.edu.au
#SBATCH --mail-type=ALL

export OMP_NUM_THREADS=1
cd $SLURM_SUBMIT_DIR
ulimit -s unlimited

~/cta/CTA-Simulation/scripts/prod4_sst-astri+chec-s_sim 6
